
---
  baseURL: 'https://dashbird.io/'
  languageCode: 'en-us'
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  author:
    name: "Dashbird"
    email: "info@dashbird.io"
  title: 'Dashbird'
  disqusShortName: 'dashbird'
  twitter_card_whitelisted: true
  outputs:
    home: ['HTML', 'RSS']
  menu:
    main:
      - name: 'Product'
        identifier: 'product'
        URL: '/features/'
        weight: 100
      - name: 'Documentation'
        identifier: 'documentation'
        URL: '/docs/'
        weight: 200
      - name: 'Pricing'
        identifier: 'pricing'
        URL: '/pricing/'
        weight: 300
      - name: 'Resources'
        identifier: 'resources'
        URL: '/resources/'
        weight: 300
  params:
    thumbnail: "images/screens/slogan.jpg"
    blog:
      title: "Dashbird - Lambda & Serverless Examples, Guides and Hot Topics"
      description: "Team behind the best Serverless monitoring software share their thoughts about development."
      canonical: "/blog/"
      date: 2017-11-05T17:50:03+02:00
  taxonomies:
    blog: "blog"
    kbSeries: "kbSeries"
  disableKinds: ["categories", "kbSeries"]
  preserveTaxonomyNames: true
  sitemap:
    changefreq: "monthly"
    priority: 1
    filename: "sitemap.xml"
