
---
  baseURL: 'https://dashbird.io/'
  languageCode: 'en-us'
  title: 'Dashbird'
  disqusShortName: 'dashbird'
  twitter_card_whitelisted: true
  outputs:
    home: ['HTML', 'JSON']
  menu:
    main:
        - Name: 'Features'
          URL: '/features/'
          Weight: 100
        - Name: 'Pricing'
          URL: '/pricing'
          Weight: 200
        - Name: 'Blog'
          URL: '/blog'
          Weight: 300
  params:
    thumbnail: "images/screens/preview.png"
  taxonomies:
    tag: "tags"
    category: "categories"
    kbSeries: "kbSeries"
  preserveTaxonomyNames: true
  sitemap:
    changefreq: "monthly"
    priority: 1
    filename: "sitemap.xml"
