
---
  baseURL: 'https://dashbird.io/'
  languageCode: 'en-us'
  title: 'Dashbird'
  menu:
    main:
        - Name: 'Features'
          URL: '/features/'
          Weight: 100
        - Name: 'Pricing'
          URL: '/pricing'
          Weight: 200
        # - Name: 'Blog'
        #   URL: '/blog'
        #   Weight: 300
        - Name: 'Team'
          URL: '/team'
          Weight: 400

