
---
  baseURL: 'https://dashbird.io/'
  languageCode: 'en-us'
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  author:
    name: "Dashbird"
    email: "info@dashbird.io"
  title: 'Dashbird'
  disqusShortName: 'dashbird'
  twitter_card_whitelisted: true
  outputs:
    home: ['HTML', 'RSS']
  mediaTypes:
    application/rss:
      suffix: xml
  menu:
    main:
        - Name: 'Product'
          URL: '/features/'
          Weight: 100
        - Name: 'Pricing'
          URL: '/pricing'
          Weight: 200
  params:
    thumbnail: "images/screens/preview.png"
  taxonomies:
    tag: "tags"
    category: "categories"
    kbSeries: "kbSeries"
  disableKinds: ["categories", "kbSeries"]
  preserveTaxonomyNames: true
  sitemap:
    changefreq: "monthly"
    priority: 1
    filename: "sitemap.xml"
