
---
  baseURL: 'https://dashbird.io/'
  languageCode: 'en-us'
  title: 'Dashbird'
  disqusShortName: 'dashbird'
  twitter_card_whitelisted: true
  menu:
    main:
        - Name: 'Features'
          URL: '/features/'
          Weight: 100
        - Name: 'Pricing'
          URL: '/pricing'
          Weight: 200
        - Name: 'Blog'
          URL: '/blog'
          Weight: 300
